#! /bin/bash

cd /home/pi/git/RGPIO

echo Compiling java files...

javac  -classpath /home/pi/git/RGPIO/lib/'*' */*.java

echo Creating jar file...

jar cvfe RGPIO.jar main/RGPIOmain */*.class  > /dev/null
mv RGPIO.jar /home/pi/git/RGPIO/lib

echo Jar file in /home/pi/git/RGPIO/lib
echo
ls -l /home/pi/git/RGPIO/lib/RGPIO.jar
echo
